// WORDS LIST CONSTANTS
export const WORDS_LIST_REQUEST = "WORDS_LIST_REQUEST";
export const WORDS_LIST_SUCCESS = "WORDS_LIST_SUCCESS";
export const WORDS_LIST_FAIL = "WORDS_LIST_FAIL";

// WORDS DETAILS CONSTANTS
export const WORDS_DETAILS_REQUEST = "WORDS_DETAILS_REQUEST";
export const WORDS_DETAILS_SUCCESS = "WORDS_DETAILS_SUCCESS";
export const WORDS_DETAILS_FAIL = "WORDS_DETAILS_FAIL";

// WORDS ADD CONSTANTS
export const WORD_ADD_REQUEST = "WORD_ADD_REQUEST";
export const WORD_ADD_SUCCESS = "WORD_ADD_SUCCESS";
export const WORD_ADD_FAIL = "WORD_ADD_FAIL";
export const WORD_ADD_RESET = "WORD_ADD_RESET";

